//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaEntities : DbContext
    {
        public BibliotekaEntities()
            : base("name=BibliotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<AuthorsBook> AuthorsBook { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<clientQuantity> clientQuantity { get; set; }
    }
}
