//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int IdRent { get; set; }
        public int IdClient { get; set; }
        public int IdBook { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateReturn { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
