//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int IdEmployee { get; set; }
        public string FirstName { get; set; }
        public string Surename { get; set; }
        public string Position { get; set; }
        public System.DateTime BirthDay { get; set; }
    }
}
